[project]
name = "openp5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==1.23.1",
    "scikit-learn==1.1.2",
    "torch>=2.5.1",
    "tqdm==4.64.1",
    "transformers==4.26.0",
    "wandb>=0.19.1",
]
